node{
    def mvnHome = tool 'jenkins-maven'
    stage('Checkout'){
        checkout scmGit(branches: [[name: '**']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/29SagarSharma/jenkins-maven-project.git']])
    }
    
    stage ('build'){
        sh "${mvnHome}/bin/mvn clean package"
    }
     stage('Scan') {
        withSonarQubeEnv('sq1') {
                sh "${mvnHome}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=jenkins-codeReport -Dsonar.organization=jenkins-290 -Dsonar.host.url=https://sonarcloud.io"
  }
}
}
